# Generated by Django 3.0.9 on 2020-08-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='title',
            new_name='name',
        ),
    ]
