# Generated by Django 3.0.9 on 2020-08-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200810_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='name',
            new_name='title',
        ),
    ]
